### ISSUE TITLE
Interface counter data stored as-is when should be stored as delta

### ISSUE THREAD

**Issue by BigTexun** [B4ckF0rw4rd/Zabbix-Templates#11]
In reviewing the results of your ASA Discovery template, I was pleased with the results, however I noted that several of the graphs were indicating odd activity on ports with nearly zero traffic.  For example, my OutUcastPkts graph for an unused VLAN was showing 19.5Mpps, but when I looked at the ASA's interface counter it was running between 2 and 8 pps.  I noticed the counter was showing  19832823 packets output, 562431516 bytes, and I realized you were graphing the counter, rather than the actual rate.  Changing the setting to store the value as a delta corrected the issue.

In the ASA template these prototypes were needing correction:
OutUcastPkts, OutMulticastPkts, OutBroadcastPkts, InUcastPkts, InMulticastPkts, InBroadcastPkts.

I saw the same issue in the Cisco Switch Discovery template, the issue there was in the following:
Inbound BroadcastPkts, MulticastPkts and UnicastPkts
Outbound BroadcastPkts, Errors, and UnicastPkts.

My notes may be incomplete, so you might take a look at all of your prototypes.  Interestingly the inbound errors were set as a delta, while the outbound errors were as-is.  So it seems clear that this is simply an oversight, and not by design.  Of course the other clue this is not by design is the reporting of a 2pps rate as 19.5Mpps.  When I saw the flat graph with 19 million packets per second on an unused vlan port, my first reaction was we were under attack.  It didn't take too long to figure out it was a template error.

**Comment by B4ckF0rw4rd** [comment]
Hi BigTexun,

Sorry for the late reply, i'm on vacation right now.

Many many thanks for the analysis, as soon as i return i'll update the
templates.

Best regards,
Manuel Mannello

**Comment by BigTexun** [comment]
No worries!  I know the open source contributions are always on an as-you-have-time basis.  Your contribution is very much appreciated, and you deserve your vacation time.  Responding within a week is outstanding.

**Comment by B4ckF0rw4rd** [comment]
It should be fixed now, thanks for the debug!
