### ISSUE TITLE
Need to install MIB

### ISSUE THREAD

**Issue by Fabian1976** [B4ckF0rw4rd/Zabbix-Templates#15]
Since you converted the OID to MIB, the MIBs from CISCO need to be imported. Maybe mention that in the README?
They can be downloaded from this location:
ftp://ftp.cisco.com/pub/mibs/v2

And add the note to share.zabbix.com

They need to download these MIBS:
* CISCO-FIREWALL-MIB.my
* CISCO-MEMORY-POOL-MIB.my
* CISCO-PROCESS-MIB.my
* CISCO-QOS-PIB-MIB.my
* CISCO-REMOTE-ACCESS-MONITOR-MIB.my
* CISCO-SMI.my
* CISCO-TC.my
* ENTITY-MIB.my

and place them in this folder on the zabbix-server or zabbix-proxy:
/usr/share/snmp/mibs

**Comment by fcafra** [comment]
Hi @Fabian1976 @B4ckF0rw4rd, I downloaded .my files for Zabbix 4.0.1 but seem not working, I try to rename .my files into .txt files but nothing. 

Have an hint for me please ?
Thanks !

**Comment by Fabian1976** [comment]
Have you restarted the proxy/server?

**Comment by fcafra** [comment]
yes,  systemctl restart zabbix-server zabbix-agent apache2

**Comment by fcafra** [comment]
Sorry again @Fabian1976,    
No Such Object available on this agent at this OID
for cpmCPUTotal1minRev, cpmCPUTotal5minRev and cpmCPUTotal5secRev,

example
snmpwalk -v 2c -c COMMUNITY IP CISCO-PROCESS-MIB::cpmCPUTotal1minRev.1
CISCO-PROCESS-MIB::cpmCPUTotal1minRev.1 = No Such Object available on this agent at this OID

can I have an help please ?

**Comment by fcafra** [comment]
@Fabian1976   on ASA 5505 working if "del" Rev,  

cpmCPUTotal1min, cpmCPUTotal5min and cpmCPUTotal5sec

**Comment by B4ckF0rw4rd** [comment]
@Fabian1976 Hi Fabian, i already tried to add the references in Zabbix Share but the external resources are filtered by the admins; i'll add your note to the ReadMe here on GitHub.
