### ISSUE TITLE
Can 't get traffic graph

### ISSUE THREAD

**Issue by mulbzh** [B4ckF0rw4rd/Zabbix-Templates#16]
Hello and sorry for my english,

I have set up this template. All works but i don't have traffic graph, 

Zabbix can get all interfaces and i can have packets graphs but i have no data for "inOctets, "outoctets"...

I don't understand why because the rest is good.

I can do also snmpwalk on ASA without errors

thanks for help

**Comment by mulbzh** [comment]
Also, i have this template on old zabbix server and it works with the same ASA

**Comment by B4ckF0rw4rd** [comment]
Hello, 

try to ask to the community of Zabbix Share, providing some evidence.

Regards,
Manuel
