### ISSUE TITLE
For zabbix 4.0 in wlc.awk need tags 

### ISSUE THREAD

**Issue by mortinelli** [B4ckF0rw4rd/Zabbix-Templates#17]
`<mappings> </mappings>`

and in this tag go's 

                <mapping>
                    <value>1</value>
                    <newvalue>unknown</newvalue>
                </mapping>
                <mapping>
                    <value>2</value>
                    <newvalue>notInstalled</newvalue>
                </mapping>
                <mapping>
                    <value>3</value>
                    <newvalue>ok</newvalue>
                </mapping>
                <mapping>
                    <value>4</value>
                    <newvalue>failed</newvalue>
                </mapping>
                <mapping>
                    <value>5</value>
                    <newvalue>highTemperature</newvalue>
                </mapping>
                <mapping>
                    <value>6</value>
                    <newvalue>replaceImmediately</newvalue>
                </mapping>

**Comment by B4ckF0rw4rd** [comment]
So you're suggesting that it need to be something like this?

        **<mappings>**
           <mapping>
                <value>1</value>
                <newvalue>unknown</newvalue>
            </mapping>
            <mapping>
                <value>..X..</value>
                <newvalue>..Y..</newvalue>
            </mapping>
        **</mappings>**

**Comment by jaydenk** [comment]
@B4ckF0rw4rd adding the above worked for me, yep.

**Comment by kalodis** [comment]
i run zabbix 4.4.3

I am super lost on this above statement. 

Where does this get inputted? 
Is there a print command in front? 

Im lost....

**Comment by B4ckF0rw4rd** [comment]
It should be fixed in the script now.
