### ISSUE TITLE
Creat trigger on VPN

### ISSUE THREAD

**Issue by mulbzh** [B4ckF0rw4rd/Zabbix-Templates#18]
Hello,

I 'd like to have alerts when active SSL VPN remote Access is use.

So when key crasIPSecNumSessions use ine the template is different from 0

I create this trigger : 
{Template Cisco ASA Discovery:crasIPSecNumSessions.last(0)}>0

 I doesn't work !

Do you think this trigger is good ?

Thanks

**Comment by B4ckF0rw4rd** [comment]
Maybe in the future, no time for develop.
