### ISSUE TITLE
Unable To Import XML

### ISSUE THREAD

**Issue by kalodis** [B4ckF0rw4rd/Zabbix-Templates#19]
When importing the XML file. I am getting an error stating

Invalid tag "/zabbix_export/value_maps/value_map(1)": unexpected tag "mapping".

help on this please?

**Comment by ahrar25** [comment]
The value mapping AP MAC -> NAME:

AP MAC: It's the corresponding AP "RADIO" MAC Address;
NAME: You can chose anithing suits to you, i've have hostnames like AP1, AP2, ecc
EXAMPLE: AP MAC -> NAME = 00:AA:BB:CC:DD:EE:FF:GG -> AP1

NOTE: The MAC must be in "UPPERCASE".

 

The regular expression @WLCs uplink interfaces

Expression: Virtual Interface
Expression type: Result is FALSE
CaseSensitive: FALSE
NOTE:

For all the people that have problems with discovery rules:

1 - You must create the Regular Expression BEFORE import the template;
2 - The REG EXP is defined with @ into the template, but when you need create it into your Zabbix you need to remove the @.

Example:

Template REG-EXP: @WLCs uplink interfaces
Zabbix REG-EXP: WLCs uplink interfaces
