### ISSUE TITLE
Zabbix 3

### ISSUE THREAD

**Issue by robbyd2** [B4ckF0rw4rd/Zabbix-Templates#3]
I got error with Autodiscovery rules on Zabbix 3, can anyone update the template for Zabbix 3 ?

**Comment by B4ckF0rw4rd** [comment]
Hi,

I'm so sorry but for now i really don't have time. I'll try to fix it as
soon as i can.
Il 4 apr 2016 4:27 PM, "robbyd2" <notifications@github.com> ha scritto:

**Comment by robbyd2** [comment]
Many thanks !! I really enjoyed it and using it for version 3 should be
great

Thx
Roberto
Il 05/apr/2016 14:31, "Manuel Mannello" <notifications@github.com> ha
scritto:

**Comment by B4ckF0rw4rd** [comment]
You're welcome. If you have time you can also try to do it by yourself.
Last time i wrongly updated the templates by upgranding zabbix itself...so
maybe it can still work :)

You need a zabbix 2.4.x with the templates already in it and than upgrade
to v 3.x

In the meantime send me the errors log, ill try to figure out what they
changed in the new zabbix.

Manuel
Il 5 apr 2016 3:04 PM, "robbyd2" <notifications@github.com> ha scritto:

**Comment by robbyd2** [comment]
I tried but my skills are not enough for us. 

I get " Invalid SNMP OID: cannot parse expression." on Discovery rules. I tried to change syntax for autodiscovery but I get something wrong. 

Roberto

**Comment by B4ckF0rw4rd** [comment]
Mmmm ok maybe they have changed the variables or the declaration way.

Can you send me one of the default templates of v3.x that uses SNMP and
discovery rules? The one for discovery interfaces should be fine.
Il 6 apr 2016 7:18 PM, "robbyd2" <notifications@github.com> ha scritto:

**Comment by robbyd2** [comment]
I think that with version 3 something has been changed
https://support.zabbix.com/browse/ZBXNEXT-2726  and
https://www.zabbix.com/documentation/3.0/manual/introduction/whatsnew300#multiple_oid_support_in_snmp_discovery
.

Maybe you will be able to change syntax to fix it.

**Comment by B4ckF0rw4rd** [comment]
Hi Roberto, i think i've fixed it, can you try it? If you'll confirm that i'll upload the fixed version into Zabbix Share.

Just look here but at my new branch Zabbix3....let me know!

Thanks,
Manuel

**Comment by robbyd2** [comment]
Thx Manuel,
where Can I download It ?  I cannot find any update on this code...

**Comment by B4ckF0rw4rd** [comment]
Look at my GitHub and change branch from master to Zabbix3 than download 
the raw file.

I can't attach the file on your request because is not allowed by github 
policies.

**Comment by robbyd2** [comment]
Sorry for that... I don't have a lot of experience of github.

I tried to import but I get that error: Invalid XML tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)/item_prototypes/item_prototype(1)": the tag "application_prototypes" is missing.

**Comment by B4ckF0rw4rd** [comment]
OK, updated with the missing tag, can you try again with the new one?

**Comment by robbyd2** [comment]
That's great!! 
It works perfectly! Now I can see all interfaces and graphs as well!

**Comment by B4ckF0rw4rd** [comment]
Good so finally fixed! I'm updating the templates on Zabbix Share now.

Thanks for the tests!
