### ISSUE TITLE
AP's as seperate hosts

### ISSUE THREAD

**Issue by axlroden** [B4ckF0rw4rd/Zabbix-Templates#5]
Are we able to create AP's as seperate hosts ? This would allow for trigger alarms if AP's went down.

**Comment by B4ckF0rw4rd** [comment]
Hi, if you have the right OID or MIB i can try to implement it. For now i've added the APs manually and attached the icmp ping template.

**Comment by B4ckF0rw4rd** [comment]
Closed, it's a feature request.
