### ISSUE TITLE
Connections trigger using wrong max value

### ISSUE THREAD

**Issue by lamaral** [B4ckF0rw4rd/Zabbix-Templates#7]
Using this template, my Zabbix Server kept triggering about the Connections usage.

Looking further into the problem, I noticed that the Max Connections Supported listed 2855, when ASA5510 specs put 50k.

I did a <code>snmpwalk -v2c \<omitted\>  .1.3.6.1.4.1.9.9.147.1.2.2.2.1</code>to the ASA and got the following:
```
SNMPv2-SMI::enterprises.9.9.147.1.2.2.2.1.3.40.6 = STRING: "number of connections currently in use by the entire firewall"
SNMPv2-SMI::enterprises.9.9.147.1.2.2.2.1.3.40.7 = STRING: "highest number of connections in use at any one time since system startup"
SNMPv2-SMI::enterprises.9.9.147.1.2.2.2.1.4.40.6 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.147.1.2.2.2.1.4.40.7 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.147.1.2.2.2.1.5.40.6 = Gauge32: 1884
SNMPv2-SMI::enterprises.9.9.147.1.2.2.2.1.5.40.7 = Gauge32: 2855
```
The OID used to retrieve the Max Connections Supported, actually retrieves the maximum number of connections since the firewall startup.

I don't know if this really was the expected behavior, but the problem is that the max value being use is not really the maximum number of supported connections.

I'll look for a parameter for the number of max supported connections.

**Comment by B4ckF0rw4rd** [comment]
Hello, sorry for the late reply!

Anyway i've tested the OIDs with a 5510 and a 5525-X, the results is 50k that is the max supported connections (you can see the same number also in ASDM when you look at the connections tab).

I think that the OID is correct because i had a situation with very very high connections (a dos problem) and it was near 45k, so a max of 50k sounds reasonable.

**Comment by markhamb** [comment]
OP is correct.  At least for current versions of ASA software 9.8.  You can verify this by looking at the history of the counter for Max Connections Supported (cfwConnectionStatValueHigh).  You will see this value changes over time.  For a 5525-X your max connections is 500,000.
https://www.cisco.com/c/en/us/products/collateral/security/asa-5500-series-next-generation-firewalls/data_sheet_c78-701808.html
